### PR TITLE
server.toml should always be at the beginning of config.toml

### PR DESCRIPTION
**Pull request by OniriCorpe**
## Problem

- in some cases, `server.toml` is not put at the beginning of the generated `config.toml`, which puts the server in error

## Solution

- ensuring that `server.toml` is at the beginning of the generated `config.toml`

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme !bullseyetestme

**Comment by yalh76** [comment]
Shouldn't we remove or rename `/etc/$app/config.d/server.toml` during upgrade ?
Or it will be integrated in `config.toml` two times ?

**Comment by OniriCorpe** [comment]
ah good point!
it's done

**Comment by OniriCorpe** [comment]
Except for `deleting checksum for /etc/$app/config.d/server.toml` I'm not sure it's really pertinent but as you want :)

(for `renaming` the file is finally replaced so it's equivalent, and for `creating the checksum` the new `ynh_add_config` makes this already for the new file)

**Comment by OniriCorpe** [comment]
I have done what is necessary to remove the checksum and improve the deletion of the `server.toml` file
If you want us to do the rest too, don't hesitate

**Comment by OniriCorpe** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Pull request merged**
