### PR TITLE
update to v0.6.6

### PR DESCRIPTION
**Pull request by yalh76**
https://git.sr.ht/~int80h/gemserv/commit/cecc6f5793983487edbff7a3cec42ac354a5b3d9
## Problem

- *there is an available [update](https://git.sr.ht/~int80h/gemserv/refs/v0.6.6)*
- *port and host have been deprecated in favor of interface*

## Solution

- *update the server.toml*
- *update 😌*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme !bullseyetestme

**Comment by OniriCorpe** [comment]
maybe we should cancel those tests and relaunch them when merging #13 to testing to free up CI time?

and rename this PR to something like "upgrading to v0.6.6 & fixing the server.toml"?

**Comment by yalh76** [comment]
!testme !bullseyetestme

**Comment by OniriCorpe** [comment]
🤞

**Pull request merged**
